default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Rails.application.credentials.dig(:database, :username, Rails.env.to_sym) %>
  password: <%= Rails.application.credentials.dig(:database, :password, Rails.env.to_sym) %>

development:
  <<: *default
  database: nokshibunan_tracking_development

test:
  <<: *default
  database: nokshibunan_tracking_test

production:
  <<: *default
  database: <%= Rails.application.credentials.dig(:database, :name, Rails.env.to_sym) %>
